licenses/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'licenses.views.home', name='home'),
    url(r'^$', 'main.views.index', name='index'),
    url(r'^manage/$', 'main.views.manage', name='manage'),
    url(r'^search/$', 'main.views.search', name='search'),
    url(r'^reload/$', 'main.views.reload', name='reload'),
    url(r'^load/$', 'main.views.load', name='load'),
    url(r'^download/$', 'main.views.download', name='download'),
    url(r'^appinfo/$', 'main.views.appinfo', name='appinfo'),
    url(r'^prices/$', 'main.views.prices', name='prices'),
    url(r'^update/$', 'main.views.update', name='update'),
    url(r'^z/$', 'main.views.z', name='z'),
    url(r'^licenses/$', 'main.views.licenses', name='licenses'),
    url(r'^computers/$', 'main.views.computers', name='computers'),

    #url(r'^static/', document_root=settings.STATIC_ROOT),
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve',
    #    {'document_root': settings.STATIC_ROOT, 'show_indexes': True }),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),



    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)            # + static(settings.STATIC_URL, document_root="/home/vitush/PycharmProjects/licenses/static")
              #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#urlpatterns += staticfiles_urlpatterns()


urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
           { 'document_root': '/licenses/staticfiles' }),
    )

main/models.py
from IPython.core.displaypub import DisplayPublisher
from django.db import models
import unicodedata

# Create your models here
class Publisher(models.Model):
    name = models.CharField(max_length=50,unique=False)

    def __unicode__(self):
        return self.name

    def get_publisher(self):
        return unicodedata.normalize('NFKD', self.name).encode('ascii','ignore')

    class Meta:
        ordering = ['name']


class Application(models.Model):
    name = models.CharField(max_length=100,unique=False)
    version = models.CharField(max_length=30,unique=False)
    publisher = models.ForeignKey(Publisher,unique=False)
    installation = models.CharField(max_length=100,unique=False,default='')
    license = models.IntegerField(default=0)
    cost = models.IntegerField(default=0)
    comment = models.CharField(max_length=250,unique=False)

    def __unicode__(self):
        return u'%s' % (self.name)

    class Meta:
        ordering = ['name']

    def get_name(self):
        return unicodedata.normalize('NFKD', self.name).encode('ascii','ignore')

    def get_version(self):
        return str(self.version)

    def get_cost(self):
        return self.cost

    def get_comment(self):
        return unicodedata.normalize('NFKD', self.comment).encode('ascii','ignore')


    def get_publisher(self):
        return unicodedata.normalize('NFKD', self.publisher).encode('ascii','ignore')

    def get_license_num(self):
        return self.license

    def get_license_txt(self):
        if  self.license == 1:
            return "Free"
        elif self.license == 2:
            return "Need license"
        return "Unknown"


class Licenses(models.Model):
    name = models.CharField(max_length=100,unique=True)
    applications = models.ManyToManyField(Application,null=True)
    owner = models.CharField(max_length=100,unique=False)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Computer(models.Model):
    name = models.CharField(max_length=30,unique=False)
    owner = models.CharField(max_length=100,unique=False)
    applications =  models.ManyToManyField(Application)
    licenses = models.ManyToManyField(Licenses)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

templates/appinfo.html
{% extends "base.html" %}




{% block page_content %}


<script xmlns="http://www.w3.org/1999/html">


        function softpedia() {

            document.getElementById('comment').value = "http://www.softpedia.com/dyn-search.php?search_term={{ app_name_short }}";
            document.getElementById('action_id').name = "action";
            document.getElementById('action_id').value = "Mark Free";

            document.getElementById("saveapp").submit();

        }
        function suggestions_change(en) {


            if (en == 0 ){
                document.getElementById('suggestions_id').value = '1';
            }else{
                document.getElementById('suggestions_id').value = '0';
            }
            document.getElementById('action_id').name = "action";
            document.getElementById('action_id').value = "reload";
            document.getElementById("saveapp").action = "/appinfo/";
            document.getElementById("saveapp").submit();


        }

</script>


<form id="saveapp" action="{{ return_page }}" method="post" name="save"> {% csrf_token %}
<input name="software" value="{{ app_id }}" type="hidden" >
<input id="suggestions_id" name="suggestions_id" value="{{ suggestions_id}}" type="hidden" >

<style type="text/css">
.appname
{
     width:500px !important;
}
    table{ font-size:0.8em; font-weight:bold; font-family:helvetica,sans-serif; }

</style>

        <div class="row">
               <div class="span3">
                  <h4>Application Info:</h4>
                </div>
               <div class="span4">
                    <a href="http://google.com/search?q={{ app_name_short_vendor}}" target="_blank">Google</a>  |
                    <a id="softpedia_url" href="http://www.softpedia.com/dyn-search.php?search_term={{ app_name_short }}
                    " target="_blank">Softpedia</a>
                </div>
        </div>


        <div class="span6">
            <br>
            <div class="row">
                <div class="span1">
                    Name
                </div>
                <div class="span3">
                    <input name="name" readonly value="{{ app_name }}" class="appname">
                </div>
            </div>
            <div class="row">
                <div class="span1">
                    Path
                </div>
                <div class="span3">
                    <input name="name" readonly value="{{ app_installation}}" >
                </div>
            </div>
            <div class="row">
                <div class="span1">
                    Version
                </div>
                <div class="span3">
                    <input name="name" readonly value="{{ app_version}}" >
                </div>
            </div>
            <div class="row">
                <div class="span1">
                    Publisher
                </div>
                <div class="span3">
                    <input name="name" readonly value="{{ app_publisher}}" >
                </div>
            </div>
            <div class="row">
                <div class="span1">
                    License
                </div>
                <div class="span3">
                    <input name="name" readonly value="{{ app_license}}" >
                </div>
            </div>
            <div class="row">
                <div class="span1">
                    cost
                </div>
                <div class="span3">
                    <input name="name"          value="{{ app_cost}}" >
                </div>
            </div>
            <br>
            <div class="row">
                <div class="span1">
                    Comment
                </div>
                <div class="span3">
                    <textarea name="comment" id="comment" rows="4">{{ app_comment }}</textarea>
                </div>
            </div>
            <div class="row">
                <br>
                <div class="span4">
                    <input name="action" type="submit" value="Mark Free"  />
                    <input name="action" type="submit" value="Mark Licensed" />
                    <input  type="hidden" id="action_id" name="action1" value="Mark Free" />
                </div>
                <div class="span3 offset6" id="suggestions_softpedia_btn_id"
                    onclick="suggestions_change({{ suggestions_enable }});">
                    <button type="button" class="btn btn-small
                    {% if suggestions_enable == '0' %} btn-primary ">Enable suggestions
                    {% else %}
                            ">Disable suggestions
                    {% endif %}
                   </button>
                </div>
            </div>
        </div>
        <div class="span3">
            <br><br><br>
             <div class="row">
                 Installed on :&nbsp;
             </div>
             <div class="row">
                <select name="pclist" size="10"">
                    {% for pc in pclist %}
                       <option value="{{pc.id}}" >{{pc.name}}</option>
                    {% endfor %}
                </select>
             </div>

        </div>

</form>


{% endblock %}


{% block page_content_softpedia %}
{% if suggestions_enable == '1' %}
    {%  if softpedia_content|length > 0 %}
    <div class="row">
    <hr>
        <div class="span8">
             <p>
                 <b>Softpedia Search Result :</b>
             </p>
        </div>
        <div class="span2">

                  <input  type="button" onclick="softpedia();" value="Mark as Free and add Softpedia URL" />
        </div>
    </div>
    <div class="row">
           {{ softpedia_content|safe }}
    </div>
    {% endif %}
{% endif %}

{% endblock %}

templates/base.html
<html lang="en">
<head>
<meta charset="utf-8">
<title>License manager</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="vitush">

{% block refresh %} {% endblock %}

<link href="/static/css/bootstrap.css" rel="stylesheet">
<style type="text/css">body{padding-top:60px;padding-bottom:40px;}</style>
<link href="/static/css/bootstrap-responsive.css" rel="stylesheet">





</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
<a class="brand" href="/">TOOL</a>

<ul class="nav nav-pills red">
    <li><a href="/computers/" data-toggle="tab">Computers</a></li>
    <li><a href="/search/" data-toggle="tab">Reports</a></li>
    <li><a href="/manage/" data-toggle="tab">Manage</a></li>
    <li><a href="/update/" data-toggle="tab">Update</a></li>
    <li><a href="/prices/" data-toggle="tab">Prices</a></li>
    <li><a href="/licenses/" data-toggle="tab">Licenses</a></li>
</ul>

</div>
</div>
</div>



<div class="container">


    {% block page %}
        <div class="row">
        {% block page_content %}

        {% endblock %}
        </div>

        {% block page_content_softpedia %}
        {% endblock %}

        {% block page_content_wikipedia %}
        {% endblock %}

    {% endblock %}


<hr>
<footer>
<p>&copy; Symphony-Solutions 2013</p>
</footer>
</div>



    </body>
</html>

templates/computers.html
{% extends "base.html" %}

{% block page_content %}


    <script>
        function deletepc(pcid) {

            document.getElementById("deletepc_id").value=pcid;
            document.getElementById("form_computers_id").submit();
            document.getElementById("form_computers_id").submit();
        }


    </script>


<div class="span12">
<h5>Computers</h5>
<form id="form_computers_id"  action="/computers/" method="post">  {% csrf_token %}

<div class="row">
    <div class="span4">
        License:&nbsp;
        <select name="license_id" id="license_id">
            {% for lc in licenses %}
                <option value="{{lc.id}}" {% if lc.id == licenses_selected %} selected {% endif %} >{{lc.name}}
                ( {{ lc.computer_set.all|length }} )
                </option>
            {% endfor %}
        </select><br>
        <input class="btn" name="action" type="submit" value="Add"  >
        <input class="btn" name="action" type="submit" value="Remove" >

    </div>
    <div class="span3">
        Computers:&nbsp;
        <select id="computer_id" name="computer_id" multiple="true" size="6" >
            {% for pc in computers%}
               <option value="{{pc.id}}" title="{{pc.owner}} " >{{pc.name}}</option>
            {% endfor %}
        </select>

    </div>
    <hr>
</div>
<div class="row">
    <input type="hidden" id="deletepc_id" name="deletepc_id" value="">
    <table class="table">
    <thead>
     <th>Computer</th>
     <th>Applayed Licenses</th>
     <th>  <input type="submit" class="btn btn-mini btn-danger" name="action" value="Delete All PC"> ({{ computers|length }})</th>
    </thead>
    <tbody>
        {% for comp  in computers %}
            <tr>
                <td title="{{ comp.name }}"> {{ comp.name }} </td>
                <td >
                    {% for lc in comp.licenses.all %}
                        <p title="License owner: {{ lc.owner }}">{{ lc.name  }}</p>
                    {% endfor %}

                </td>
                <td>
                    <input type="submit" class="btn btn-mini btn-warning" name="action" value="Delete PC" onclick="deletepc({{ comp.id }})">
                </td>
            </tr>
        {%  endfor %}
    </tbody>
    </table>
</div>



</form>
</div>


{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block page_content %}

<div class="span4">
<h2>Licenses</h2>
<p>Licenses management tool</p>
</div>



{% endblock %}

templates/licenses.html
{% extends "base.html" %}

{% block page_content %}

    <script>
        function license_change() {

            //var e = document.getElementById("licenses");
            //var license_id = e.options[e.selectedIndex].value;

            //document.getElementById("licenses_id").value='changelicense';
            document.getElementById("action_id").value='changelicense';
            document.getElementById("form_licenses").submit();
        }


    </script>


<style type="text/css">
.selectwidthauto
{
     width:350px !important;
}
.selectwidthauto1
{
     width:500px !important;
}
</style>


<form id="form_licenses"  action="/licenses/" method="post">  {% csrf_token %}
<div class="span4">
<h5>License </h5>


        <input type="hidden" id="action_id" name="action" >
       <div class="row">
            <p>
                License:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <select name="licenses" id="licenses" onchange="license_change();">
                    {% for lc in licenses %}
                        <option value="{{lc.id}}" {% if lc.id == licenses_selected_id  %} selected {% endif %}>{{lc.name}}</option>
                    {% endfor %}
                </select></p>

        </div>

        <div class="row ">
            New License:&nbsp;
            <input type="text" name="license_name" id="license_name_id" value=""> <br>
            License owner:&nbsp;
            <input type="text" name="license_owner" id="license_owner_id" value=""> <br>
        </div>
        <br><br>
        <div class="row align-right">
            <input class="btn " type="submit" name="action" value="Add License">
            <input class="btn " type="submit" name="action" value="Remove License"> <br>
        </div>


</div>

<div class="span4">
<h5>Include</h5>

            <select id="applications_included" name="applications_included"  multiple="true" size="10" class="selectwidthauto">
                {% for app in applications_included %}
                   <option value="{{app.id}}"
                           title="{{app.name}}">{{app.name}}</option>
                {% endfor %}
            </select>
        <br>
         <input class="btn "  name="action"   type="submit" value="Remove Software" onclick="remove_app();"> <br>

</div>

<div class="span4">
<h5>Not Include</h5>

            <select id="software_licensed" name="software_licensed" multiple="true" size="10" class="selectwidthauto">
                {% for app in software_licensed %}
                   <option value="{{app.id}}"
                           title="{{app.name}}">{{app.name}}</option>
                {% endfor %}
            </select>
         <br>
         <input class="btn "  name="action"  type="submit" value="Add Software" "> <br>

</div>
</form>
{% endblock %}

templates/load.html
{% extends "base.html" %}

{% block refresh %}
    <meta http-equiv="refresh" content="1" >
{% endblock %}

{% block page_content %}
    <div class="progress">
      <div class="bar" style="width: {{ progress_level }}%;"></div>
    </div>
    <div>
        Progress {{ progress_level }}  % <br>
        Loading: {{ current_file }} ...  <br>
        Found: {{ last_sw }} <br>
    </div>
{% endblock %}

templates/manage.html
{% extends "base.html" %}

{% block page_content %}

    <script>
        function swinfo(form_id) {

            document.getElementById(form_id).action='/appinfo/';
            document.getElementById(form_id).submit();

        }
        function gotoprices(form_id) {

            document.getElementById(form_id).action='/appinfo/';
            document.getElementById(form_id).submit();

        }

        //function jumpToIndex(var index) {
        //    var list = document.getElementByID('" + this.list.ClientID + "');
        //    for(var i=0; i < list.length; i++) {
        //        if(list.options[i].value.charAt(0) == index) {
        //          HOW TO SET THE SCROLL POSITION TO MAKE THAT OBJECT THE TOP OF THE LIST BOX
        //          break; //pretty sure this is how i would break out of both loops.
        //        }
        //    }
        //}

    </script>

<style type="text/css">
.selectwidthauto
{
     width:350px !important;
}
.selectwidthauto1
{
     width:500px !important;
}
</style>


<div class="span4">
<h5>License type unknown  (<b>{{ unknown_software|length }}</b>)</h5>
        <form id="unknown_software_id"  action="/manage/" method="post">  {% csrf_token %}
            <select id="unknown_software_id_select" name="software" multiple="true" size="20" title="Unknown license type" class="selectwidthauto"  ">
                {% for sw in unknown_software %}
                   <option value="{{sw.id}}" ondblclick="swinfo('unknown_software_id');"

                           title="{{sw}} ({{sw.publisher}})">{{sw}}</option>
                {% endfor %}
            </select>

        <p>
        <input name="action" type="submit" value="Mark Free"  />
        <input name="action" type="submit" value="Mark Licensed" />
       </p>
   </form>
</div>

<div class="span4">
<h5>Free software (<b>{{ free_software|length }}</b>)</h5>
        <form id="free_software_id" action="/manage/" method="post">  {% csrf_token %}
            <select id="free_software_id_select" name="software" multiple="true" size="20" title="Unknown license type" class="selectwidthauto">
                {% for sw in free_software %}
                   <option value="{{sw.id}}" ondblclick="swinfo('free_software_id');" title="{{sw}} ({{sw.publisher}})" >{{sw}}</option>
                {% endfor %}
            </select>
        <p>
        <input name="action" type="submit" value="Mark Unknown"  />
        <input name="action" type="submit" value="Mark Licensed" />
        </p>
   </form>
</div>

<div class="span4">
<h5>Software require license (<b>{{ licensed_software|length }}</b>)</h5>
        <form id="licensed_software_id"  action="/manage/" method="post">  {% csrf_token %}
            <select id="licensed_software_id_select" name="software" multiple="true" size="20" title="Need License" class="selectwidthauto1">
                {% for sw in licensed_software %}
                   <option value="{{sw.id}}"
                           ondblclick="swinfo('licensed_software_id');"
                           title="{{sw}} ({{sw.publisher}}) " >
                        {{sw}} {% if sw.cost > 0 %} [ {{ sw.cost }} UAH ]  {% endif %}  </option>
                {% endfor %}
            </select>

        <p>
        <input name="action" type="submit" value="Mark Unknown"  />
        <input name="action" type="submit" value="Mark Free" />
        <input name="action" type="submit" value="Prices" />
        </p>
           </form>
</div>



{% endblock %}

templates/price.html
{% extends "base.html" %}

{% block page_content %}

    <script>
        function swinfo(sw_id) {

            document.getElementById("form_software_id").action='/appinfo/';
            document.getElementById("software").value = sw_id;
            document.getElementById("form_software_id").submit();

        }
    </script>

<style type="text/css">

table {
    table-layout: fixed;
    word-wrap: break-word;
    font-size: 14px;
}
.table th.rightCell,
.table td.rightCell {
  text-align: right;
}
</style>

<div class="span12">
<h5>Software require license (<b>{{ licensed_software|length }}</b>)</h5>
<form id="form_software_id"  action="/appinfo/" method="post">  {% csrf_token %}
<input type="hidden" name="software" id="software" value="0">

<table class="table">
<thead>
 <th>Application</th>
 <th class="rightCell" width="10%">Cost</th>
 <th width="20%">Comment</th>
 <th class="rightCell" width="10%"> Computers </th>
</thead>
<tbody>
    {% for sw in licensed_software %}
        <tr ondblclick="swinfo({{ sw.id }});" >
            <td title="{{ sw.name }}"> {{ sw.name }} </td>
            <td class="rightCell" > {{ sw.cost }} UAH</td>
            <td>{%  if sw.comment|length > 0 %}
                    <a target="_blank" href="{{ sw.comment }}" title="{{ sw.comment }}">
                    {{ sw.comment|slice:":20" }} ...</a>
                {% endif %}</td>

            <td title="{%  for pc in sw.computer_set.all %}
                    {{ pc.name }}{% endfor %}">
                {%  if sw.computer_set.all|length  == 0  %}
                   <span class="label">( {{ sw.computer_set.all|length }} )</span>
                {% elif sw.computer_set.all|length  < 10 %}
                    <span class="label label-warning">( {{ sw.computer_set.all|length }} )</span>
                {% else %}
                    <span class="label label-important">( {{ sw.computer_set.all|length }} )</span>
                {% endif %}</td>

        </tr>
    {%  endfor %}
</tbody>
</table>

</form>
</div>



{% endblock %}

templates/report_pc.html
{% extends "base.html" %}

{% block page_content %}

<style type="text/css">
.selectwidthauto
{
     width:250px !important;
}
</style>
    <script>
        function swinfo(form_id) {

            document.getElementById(form_id).action='/appinfo/';
            document.getElementById(form_id).submit();

        }
    </script>


 <p>
     <form action="/download/" name="download" method="post"> {% csrf_token %}
             <input type="hidden" name="computer_id" value="{{ computer_id }}"/>
             <input type="submit" name="download" value="Download Report"/>

     </form>
 </p>

<div class="span4">
<h4>License type unknown</h4>
        <form id="unknown_software_id" action="/report_pc/" method="post">  {% csrf_token %}
            <select name="software" multiple="true" size="10" title="Unknown license type" class="selectwidthauto">
                {% for sw in unknown_software %}
                   <option value="{{sw.id}}" ondblclick="swinfo('unknown_software_id');"  title="{{sw}} ({{sw.publisher}})" >{{sw}}</option>
                {% endfor %}
            </select>
        </form>

</div>

<div class="span4">
<h4>Free software</h4>
        <form id="free_software_id" action="/report_pc/" method="post">  {% csrf_token %}
            <select name="software" multiple="true" size="10" title="Unknown license type" class="selectwidthauto">
                {% for sw in free_software %}
                   <option value="{{sw.id}}" ondblclick="swinfo('free_software_id');"  title="{{sw}} ({{sw.publisher}})">{{sw}}</option>
                {% endfor %}
            </select>
        </form>
</div>

<div class="span4">
<h4>Software require license</h4>
        <form id="licensed_software_id" action="/report_pc/" method="post">  {% csrf_token %}
            <select name="software" multiple="true" size="10" title="Need License" class="selectwidthauto">
                {% for sw in licensed_software %}
                   <option value="{{sw.id}}" ondblclick="swinfo('licensed_software_id');"  title="{{sw}} ({{sw.publisher}})">{{sw}}</option>
                {% endfor %}
            </select>
        </form>
</div>


{% endblock %}

templates/reports.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

templates/search.html
{% extends "base.html" %}

{% block page_content %}

<p>
     <form action="/download/" name="download" method="post"> {% csrf_token %}
             <input type="hidden" name="computer_id" value="all"/>
             <input type="submit" name="download" value="Download Total Report"/>
             <input type="submit" name="download" value="Download Total Report (Only Licensed)"/>
     </form>
 </p>

<h2> Filter : </h2>

     <form action="/search/"  method="post" > {% csrf_token %}
		<p>
			PC name :&nbsp;
            <select name="computer" onchange="combo(this, 'computer')">
                {% for pc in list_pcs %}
                    <option value="{{pc.id}}">{{pc}}</option>
                {% endfor %}
            </select></p>
		<p>
			Publisher :&nbsp;
            <select name="publisher" onchange="combo(this, 'publisher')">
                    <option value="all">All</option>
                {% for pub in list_publishers %}
                    <option value="{{pub.id}}">{{pub}}</option>
                {% endfor %}
            </select></p>
        <p>
             <input type="submit" value="Show Selected Software">
        </p>
     </form>

{% endblock %}

templates/test.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

templates/update.html
{% extends "base.html" %}

{% block page_content %}

<div class="span4">
<h2>Update</h2>
<p>Reload XML Files.</p>
<p><a class="btn btn-primary" href="/reload/">Reload XML Data&raquo;</a></p>
</div>

{% endblock %}

templates/z.html
{% extends "base.html" %}

{% block page_content %}

    <table class="table">
        <thead>
         <th> Old name</th>
         <th> Naw name</th>
        </thead>
        <tbody>
            {% for app in new  %}
            <tr>
                <td>
                    {{ app.name }}
                </td>
                <td>
                    {{ app.name1 }}
                </td>

            </tr>
            {% endfor %}
        </tbody>

    </table>

{% endblock %}